### ISSUE TITLE
Please add libmosquitto

### ISSUE THREAD

**Issue by ralight** [lvc/upstream-tracker#10]
Hello,

I've been using a (now out of date) version of abi-monitor for a while now, thanks it's a useful tool to have in the background. I didn't see that you'd got a public tracker set up, would you consider tracking my library libmosquitto? I've attached the mosquitto.json and build.sh that I have been using - I wasn't sure what you'd want out of them so I've not made this a pull request.

[mosquitto.json](https://github.com/lvc/upstream-tracker/files/1158809/mosquitto.txt)
[build.sh](https://github.com/lvc/upstream-tracker/files/1158812/build.txt)

Thanks,

Roger

**Comment by lvc** [comment]
Hello,

The report has been added here: https://abi-laboratory.pro/tracker/timeline/mosquitto/

Thank you.

![mosquitto-2](https://user-images.githubusercontent.com/1517837/28403055-fd700a26-6d33-11e7-8bcb-08d08ff524ed.png)
![mosquitto-1](https://user-images.githubusercontent.com/1517837/28403049-f615c82e-6d33-11e7-933f-be109c82d352.png)

**Comment by ralight** [comment]
Brilliant, thanks very much.
