### ISSUE TITLE
Add LLVM's OpenMP

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#11]
Would be great to have [LLVM's OpenMP]( http://openmp.llvm.org/ ) library (they call it `openmp`) added to the tracker.

**Comment by lvc** [comment]
Hello,

The report has been added here: https://abi-laboratory.pro/tracker/timeline/llvm_openmp/

Thank you.

![llvm_openmp-1](https://user-images.githubusercontent.com/1517837/28403230-e675ec86-6d34-11e7-9e93-dc4880b993c9.png)
![llvm_openmp-2](https://user-images.githubusercontent.com/1517837/28403234-ec5a3e2c-6d34-11e7-9d5c-4d8930084050.png)

**Comment by jakirkham** [comment]
Great thanks for both of these. :)
