### ISSUE TITLE
Add lzo

### ISSUE THREAD

**Issue by dougalsutherland** [lvc/upstream-tracker#12]
It'd be nice to have lzo in the tracker. https://github.com/conda-forge/conda-forge.github.io/pull/410 would appreciate the info, for example. :)

**Comment by lvc** [comment]
Hi,

The report for the library has been added here: 

LZO: https://abi-laboratory.pro/tracker/timeline/lzo/
miniLZO: https://abi-laboratory.pro/tracker/timeline/minilzo/

Thank you.

![lzo-1](https://user-images.githubusercontent.com/1517837/28474934-7ba38f44-6e5b-11e7-95ff-2f073f861983.png)
![lzo-2](https://user-images.githubusercontent.com/1517837/28474943-852fe1b6-6e5b-11e7-897c-e8e4f01ad967.png)

**Comment by dougalsutherland** [comment]
Perfect, thanks!
