### ISSUE TITLE
Add arpack

### ISSUE THREAD

**Issue by dougalsutherland** [lvc/upstream-tracker#13]
Would appreciate having arpack as well, c.f. https://github.com/conda-forge/conda-forge.github.io/pull/406

**Comment by lvc** [comment]
The report for the library has been added at: https://abi-laboratory.pro/tracker/timeline/arpack-ng/

Please note that analysis of FORTRAN libraries is now in Beta.

Thank you.

![arpack-ng-1](https://user-images.githubusercontent.com/1517837/28475037-dd8ea586-6e5b-11e7-987a-797d7c175afa.png)
![arpack-ng-2](https://user-images.githubusercontent.com/1517837/28475053-e5f7e728-6e5b-11e7-8fde-ac67fcdcd213.png)

**Comment by dougalsutherland** [comment]
Great, thank you!
