### ISSUE TITLE
Add openlibm

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#15]
Would be nice to add [`openlibm`]( https://github.com/JuliaLang/openlibm ) to the tracker. This is a portable, open source `libm` implementation. Used by [`julia`]( https://github.com/JuliaLang/julia ) and packaged by many Linux distros.

**Comment by lvc** [comment]
Report: https://abi-laboratory.pro/tracker/timeline/openlibm/

![openlibm-1](https://user-images.githubusercontent.com/1517837/30847949-6b98004e-a2ae-11e7-9eca-3bb3a332cb93.png)
![openlibm-2](https://user-images.githubusercontent.com/1517837/30847955-7164ce94-a2ae-11e7-8f3d-a924fba85553.png)

**Comment by jakirkham** [comment]
Great, thanks!
