### ISSUE TITLE
Add openspecfun

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#16]
Would be nice to add [`openspecfun`]( https://github.com/JuliaLang/openspecfun ) to the tracker.

**Comment by lvc** [comment]
Report: https://abi-laboratory.pro/tracker/timeline/openspecfun/

![openspecfun-1](https://user-images.githubusercontent.com/1517837/30900941-edc01714-a376-11e7-818d-1b86f1d6603f.png)
![openspecfun-2](https://user-images.githubusercontent.com/1517837/30900949-f33a2aea-a376-11e7-906c-3cef85ba2bb8.png)

**Comment by jakirkham** [comment]
Perfect. Thanks!
