### ISSUE TITLE
Add suitesparse

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#17]
Would be great to have [suitesparse]( http://faculty.cse.tamu.edu/davis/suitesparse.html ) included.

FWIW shared libraries are only a thing in 4.5+. Only static libraries exist in 4.4 and before, but some users built their own shared libraries anyways.

**Comment by lvc** [comment]
Report: https://abi-laboratory.pro/tracker/timeline/suitesparse/

![suitesparse-1](https://user-images.githubusercontent.com/1517837/30901027-5042c102-a377-11e7-8197-416ba1a80a72.png)
![suitesparse-2](https://user-images.githubusercontent.com/1517837/30901034-5535aa8a-a377-11e7-89b2-c4dd45a1aef8.png)

**Comment by jakirkham** [comment]
Great! Thanks for adding this.
