### ISSUE TITLE
Add icu

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#19]
Would be good to have icu in the tracker.

**Comment by lvc** [comment]
Report for ICU4C: https://abi-laboratory.pro/tracker/timeline/icu4c/

The analysis is done for the library built with `--disable-renaming` option (prevent version prefixes to be added to all symbols).

![icu4c-1](https://user-images.githubusercontent.com/1517837/30848218-8784aa86-a2af-11e7-9284-73b8a225463b.png)
![icu4c-2](https://user-images.githubusercontent.com/1517837/30848226-8d0e45de-a2af-11e7-908d-dec7647c5719.png)

There is also report for the Java edition of the library (ICU4J): https://abi-laboratory.pro/java/tracker/timeline/icu4j/

Thank you.

**Comment by jakirkham** [comment]
Perfect. Thanks!
