### ISSUE TITLE
Add libevent

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#2]
Please add `libevent` to the tracker.

Note: Would help, but am unclear how.

**Comment by lvc** [comment]
Hello,

The report for the library has been added at: http://abi-laboratory.pro/tracker/timeline/libevent/

It's updated according to the schedule: http://abi-laboratory.pro/index.php?view=upstream-tracker

Thank you for adding libraries and feel free to add more libraries to the tracker.

**Comment by jakirkham** [comment]
Awesome. Thanks.
