### ISSUE TITLE
Add libblitz

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#20]
Would be nice to include `libblitz` in the tracker.

**Comment by lvc** [comment]
Blitz++ is a template library. Only a little part of the API (<1%) is exported from the `libblitz` shared object. So the `abi-dumper` and `abi-tracker` are useless in this case.

One can try to use `abi-compliance-checker` to compare header files of old and new versions manually: https://github.com/lvc/abi-compliance-checker

Like it was done here for old library versions: http://upstream.rosalinux.ru/versions/blitz.html

![blitz-1](https://user-images.githubusercontent.com/1517837/30850175-b7ec7c52-a2b5-11e7-9f59-5e769aa7bdc3.png)

**Comment by jakirkham** [comment]
Good point. Thanks.
