### ISSUE TITLE
add other version of editline

### ISSUE THREAD

**Issue by dougalsutherland** [lvc/upstream-tracker#21]
The currently tracked version of editline is https://github.com/troglobit/editline/.

It would be nice to also track this one: http://thrysoee.dk/editline/. It's a separate project despite having the same name, unfortunately, and conda-forge uses the latter one.

**Comment by jakirkham** [comment]
Should add the second one is NetBSD's Editline. It could easily be added as libedit, which is a common "nickname".

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/libedit/

Feel free to add more libraries.

Thank you.

![libedit-2](https://user-images.githubusercontent.com/1517837/32361720-16c7d9d4-c074-11e7-8e4c-ffa82f7c2646.png)
![libedit-1](https://user-images.githubusercontent.com/1517837/32361721-16e721a4-c074-11e7-9b1a-c07d6c6fa62a.png)
