### ISSUE TITLE
add brotli

### ISSUE THREAD

**Issue by dougalsutherland** [lvc/upstream-tracker#24]
Would be nice to track brotli: https://github.com/google/brotli/releases.

**Comment by lvc** [comment]
Added at https://abi-laboratory.pro/tracker/timeline/brotli/.

Thank you.

![brotli-2](https://user-images.githubusercontent.com/1517837/34659200-3f9a7a36-f447-11e7-8a6f-0b28d981f393.png)
![brotli-1](https://user-images.githubusercontent.com/1517837/34659201-3fb63366-f447-11e7-9e56-bc5499483388.png)
