### ISSUE TITLE
Request for addition of libjit to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#26]
https://www.gnu.org/software/libjit/

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/libjit/

![libjit-1](https://user-images.githubusercontent.com/1517837/35610772-af92b716-0673-11e8-9f5b-72fd21504cfe.png)

Thanks for requesting libraries! Feel free to request more!
