### ISSUE TITLE
Add GnuTLS

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#27]
Would be nice to track [GnuTLS]( https://www.gnutls.org/ ). A library implementing various security protocols for communicating over the network.

**Comment by lvc** [comment]
It's here: https://www.gnutls.org/abi-tracker/timeline/gnutls/

But not updated for a while.

Looks like we need to set up one more instance of the tracker for better availability.

**Comment by jakirkham** [comment]
Great thanks. Sorry, I thought I looked, but must have missed it.

Should I leave this open for updating it or would you rather track that in a different issue?

**Comment by lvc** [comment]
Let's leave it open. I'm working on adding own tracker for GnuTLS currently.

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/gnutls/

![gnutls-1](https://user-images.githubusercontent.com/1517837/36337595-cf971c8e-13aa-11e8-9c7c-c60a7702a58c.png)
![gnutls-2](https://user-images.githubusercontent.com/1517837/36337594-cf759b0e-13aa-11e8-8873-a910a275441c.png)

**Comment by jakirkham** [comment]
Thank you. :)
