### ISSUE TITLE
Add xerces-c

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#29]
Would be nice to include [`xerces-c`]( http://xerces.apache.org/xerces-c/ ).

**Comment by lvc** [comment]
Report for xerces-c: https://abi-laboratory.pro/tracker/timeline/xerces-c/

![xerces-c-1](https://user-images.githubusercontent.com/1517837/36558222-6ac231ca-181b-11e8-8b11-556e28130e45.png)
![xerces-c-2](https://user-images.githubusercontent.com/1517837/36558221-6a9a90fc-181b-11e8-9e3d-1a6ffa37c208.png)

**Comment by jakirkham** [comment]
Great, thanks. :)
