### ISSUE TITLE
Add blosc

### ISSUE THREAD

**Issue by dougalsutherland** [lvc/upstream-tracker#30]
Would be nice to have `blosc` in the tracker: https://github.com/Blosc/c-blosc.

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/c-blosc/

Thanks for requesting new libraries!

![c-blosc-2](https://user-images.githubusercontent.com/1517837/36916667-af0cd934-1e65-11e8-9787-c6f380f81220.png)
![c-blosc-1](https://user-images.githubusercontent.com/1517837/36916668-af2b3b36-1e65-11e8-8c43-08bd30c82baf.png)

**Comment by jakirkham** [comment]
Thank you both. :)
