### ISSUE TITLE
GNU SASL

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#31]
Would be great to have [GNU SASL]( https://www.gnu.org/software/gsasl/ ) in the tracker. Slight preference for the name `libgsasl` in the tracker.

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/libgsasl/

![libgsasl-1](https://user-images.githubusercontent.com/1517837/37304389-85b763bc-2642-11e8-9cf8-107b35604524.png)

![libgsasl-2](https://user-images.githubusercontent.com/1517837/37304388-8599fdc2-2642-11e8-88bb-2dbf866bf2f4.png)

**Comment by jakirkham** [comment]
Thank you. :)
