### ISSUE TITLE
Libntlm

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#32]
Would be great to have [Libntlm]( https://www.nongnu.org/libntlm/ ) in the tracker.

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/libntlm/

![libntlm-2](https://user-images.githubusercontent.com/1517837/37304485-c07c695c-2642-11e8-976f-864b890832d5.png)
![libntlm-1](https://user-images.githubusercontent.com/1517837/37304486-c0983308-2642-11e8-92b0-6de66692599f.png)

**Comment by jakirkham** [comment]
Thanks. :)
