### ISSUE TITLE
Request for addition of libjasper to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#36]
https://github.com/mdadams/jasper

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/jasper/

![jasper-2](https://user-images.githubusercontent.com/1517837/37308744-0018ebdc-2650-11e8-8b30-855e8ebe14fa.png)
![jasper-1](https://user-images.githubusercontent.com/1517837/37308746-0037ac2a-2650-11e8-9d68-1c57b3e90beb.png)
