### ISSUE TITLE
Add RHash

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#38]
Would be nice to add [`rhash`]( https://github.com/rhash/RHash ) to the tracker.

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/rhash/

![rhash-2](https://user-images.githubusercontent.com/1517837/37563063-5a77fca2-2a89-11e8-905f-0ba0b9ecf129.png)
![rhash-1](https://user-images.githubusercontent.com/1517837/37563064-5a9c8306-2a89-11e8-8e00-71695ff075e7.png)
