### ISSUE TITLE
Request for addition of embree to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#39]
https://github.com/embree/embree/

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/embree/

![embree-2](https://user-images.githubusercontent.com/1517837/37564667-9e50c374-2aab-11e8-89cc-efafa1ee2251.png)
![embree-1](https://user-images.githubusercontent.com/1517837/37564668-9e6bfd9c-2aab-11e8-86b7-96edc1fe1d61.png)
