### ISSUE TITLE
Request for addition of udis86 to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#41]
https://github.com/vmt/udis86

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/udis86/

![udis86-2](https://user-images.githubusercontent.com/1517837/38655356-c8904dd8-3e1c-11e8-90b0-524f362ea544.png)
![udis86-1](https://user-images.githubusercontent.com/1517837/38655357-c8ad0428-3e1c-11e8-89da-c1ddcc3d2a7e.png)
