### ISSUE TITLE
Request for addition of libmysqlclient to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#42]
https://dev.mysql.com/downloads/connector/c/

There is a naming problem here. It's also called mysql-connector-c (ugh 🙁)

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/mysql-connector-c/

Thank you for requesting new libraries.

![mysql-connector-c-1](https://user-images.githubusercontent.com/1517837/38862851-bc52a2a2-423e-11e8-8fa5-f8250440270f.png)

**Comment by nehaljwani** [comment]
As one can see, the library name is ending in a '.' at https://abi-laboratory.pro/tracker/objects_report/mysql-connector-c/6.1.10/6.1.11/report.html

You may want to modify the cmake arguments in your build script to add:  
`-DSHARED_LIB_PATCH_VERSION="0"`
