### ISSUE TITLE
x264 is out-of-date

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#43]
The most recent release for `x264` on the tracker is from 2017. However there have been several releases this year. Would be good if this could be refreshed a bit.

ref: https://abi-laboratory.pro/tracker/timeline/x264/
ref: http://download.videolan.org/pub/videolan/x264/snapshots/

**Comment by lvc** [comment]
Fixed. Thank you.

![x264-1](https://user-images.githubusercontent.com/1517837/39403223-87cf4c58-4b7e-11e8-8329-fbed9c415d46.png)

**Comment by jakirkham** [comment]
Thanks :)
