### ISSUE TITLE
Request for addition of libaio to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#44]
Old versions at: http://libaio.sourcearchive.com/

New versions from: http://ftp.de.debian.org/debian/pool/main/liba/libaio/libaio_xxx.orig.tar.gz

**Comment by lvc** [comment]
https://abi-laboratory.pro/tracker/timeline/libaio/

![libaio-1](https://user-images.githubusercontent.com/1517837/39660289-3dfd7012-5044-11e8-879e-7f555edba81f.png)
![libaio-2](https://user-images.githubusercontent.com/1517837/39660288-3ddbee10-5044-11e8-8107-dcfb702e6d27.png)
