### ISSUE TITLE
Request for addition of libnuma to the tracker 

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#46]
libnuma is provided by https://github.com/numactl/numactl

**Comment by lvc** [comment]
Done: https://abi-laboratory.pro/tracker/timeline/libnuma/

![libnuma-2](https://user-images.githubusercontent.com/1517837/39856551-0c1d94de-5439-11e8-9b5c-d2acdea1441e.png)
![libnuma-1](https://user-images.githubusercontent.com/1517837/39856552-0c38512a-5439-11e8-835b-90f0acdd3a41.png)
