### ISSUE TITLE
Request for addition of libutf8proc to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#48]
https://github.com/JuliaLang/utf8proc/releases

**Comment by lvc** [comment]
Hi,

https://abi-laboratory.pro/?view=timeline&l=utf8proc

![utf8proc-1](https://user-images.githubusercontent.com/1517837/41086094-9e60a9b2-6a41-11e8-884d-bd8d9fd73592.png)
