### ISSUE TITLE
Add occt

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#49]
Would be great to add `occt` a.k.a Open Cascade Technology.

ref: https://en.wikipedia.org/wiki/Open_Cascade_Technology

**Comment by lvc** [comment]
Report: https://abi-laboratory.pro/?view=timeline&l=opencascade

![opencascade-1](https://user-images.githubusercontent.com/1517837/41156954-af9d45f0-6b2c-11e8-97c8-36f25bb4fd1a.png)

**Comment by jakirkham** [comment]
Thank you :)
