### ISSUE TITLE
Feature Request - Add LAPACK to tracker

### ISSUE THREAD

**Issue by isuruf** [lvc/upstream-tracker#53]
Development repo at https://github.com/Reference-LAPACK/lapack

**Comment by lvc** [comment]
https://abi-laboratory.pro/?view=timeline&l=lapack

![lapack-1](https://user-images.githubusercontent.com/1517837/43851397-3cfb1e68-9b43-11e8-8fd0-2b5b8db53955.png)

**Comment by isuruf** [comment]
Thanks
