### ISSUE TITLE
Request for info on libcxxabi (6.0.1)

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#57]
The link at https://abi-laboratory.pro/?view=timeline&l=libcxxabi provides info only till 4.0.0

**Comment by lvc** [comment]
Fixed. Thank you.

![libcxxabi-1](https://user-images.githubusercontent.com/1517837/45407174-50ebf200-b671-11e8-84ed-83e576655a2f.png)

**Comment by nehaljwani** [comment]
v7.0.0 was released recently ;-)

**Comment by lvc** [comment]
Fixed. Thank you.
