### ISSUE TITLE
Adding Tesseract

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#58]
[Tesseract]( https://github.com/tesseract-ocr/tesseract ) is an OCR library being developed by Google that can be used with OpenCV and other applications. Would be great to have it in the tracker.

**Comment by lvc** [comment]
It's here: https://abi-laboratory.pro/?view=timeline&l=tesseract

![tesseract-1](https://user-images.githubusercontent.com/1517837/45406295-bf7b8080-b66e-11e8-9edc-148bf6c8d5da.png)

**Comment by jakirkham** [comment]
Thank you :)
