### ISSUE TITLE
Adding Leptonica

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#59]
[Leptonica]( https://github.com/DanBloomberg/leptonica ) is an image processing library that can be used with OpenCV, Tesseract, etc.. Would be great to have it in the tracker.

**Comment by lvc** [comment]
It's here: https://abi-laboratory.pro/?view=timeline&l=leptonica

![leptonica-1](https://user-images.githubusercontent.com/1517837/45406386-08333980-b66f-11e8-9ef4-e77e3d28ab44.png)

**Comment by jakirkham** [comment]
Thank you :)
