### ISSUE TITLE
llvm_openmp out-of-date

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#60]
Appears the most recent version of `llvm_openmp` is 5.0.2, but LLVM is now at 7.0.0.

**Comment by lvc** [comment]
This is due to `curl http://releases.llvm.org/download.html` began to return garbage for some reason.

Let's track https://mirror.slackbuilds.org/slackware/slackware-current/source/d/llvm/ instead.

Fixed: https://abi-laboratory.pro/index.php?view=timeline&l=llvm_openmp

Thank you.

**Comment by lvc** [comment]
![llvm_openmp-3](https://user-images.githubusercontent.com/1517837/46246112-554e3400-c401-11e8-9aa2-e2ecce9cf700.png)
