### ISSUE TITLE
Request for addition of libtheora to the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#61]
https://www.theora.org/downloads/

**Comment by lvc** [comment]
Latest release was 8 years ago. Do we need it in the tracker?

See https://ftp.osuosl.org/pub/xiph/releases/theora/.

See reports in the old tracker: http://upstream.rosalinux.ru/versions/libtheora.html

**Comment by nehaljwani** [comment]
Okay, makes sense. At least the old tracker has it.
