### ISSUE TITLE
Request for updating openssl versions in the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#64]
https://abi-laboratory.pro/index.php?view=timeline&l=openssl

1.1.1a, 1.1.0j and 1.0.2q are out.

**Comment by lvc** [comment]
Fixed: https://abi-laboratory.pro/?view=timeline&l=openssl

The server was on "vacations" last week.

![openssl-1](https://user-images.githubusercontent.com/1517837/49082641-57930a00-f25b-11e8-9622-fb960c8d0e01.png)
