### ISSUE TITLE
JasPer missing 1.900 releases

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#69]
Appears the JasPer only shows the 2.0.x series, but not the 1.900.x series. Would be nice to have the 1.900.x series as well.

ref: https://abi-laboratory.pro/?view=timeline&l=jasper

**Comment by lvc** [comment]
Added, but looks like 1.900.* are just old pre-release versions.

**Comment by jakirkham** [comment]
Thanks for your help.

We unfortunately have most of our stack pinned to the old versions. Switching to 2.0.x caused a lot of breakage, which we are trying to sort out.

**Comment by lvc** [comment]
@jakirkham 

Added reports for 1.701 - 1.900.30 versions.
