### ISSUE TITLE
Add libmad

### ISSUE THREAD

**Issue by jakirkham** [lvc/upstream-tracker#7]
Would be nice to include `libmad` in the list of tracked libraries.

**Comment by lvc** [comment]
Hi,

Where can I find latest releases of libmad?

Thank you.

**Comment by jakirkham** [comment]
Sorry for the delay. Missed this one apparently. The FTP URL is below.

ref: ftp://ftp.mars.org/pub/mpeg/

**Comment by lvc** [comment]
The report has been added here: https://abi-laboratory.pro/tracker/timeline/libmad/

Thank you.

![libmad-1](https://user-images.githubusercontent.com/1517837/28403152-7a6342fa-6d34-11e7-854a-3f4f5fa84155.png)
![libmad-2](https://user-images.githubusercontent.com/1517837/28403159-82336500-6d34-11e7-8dd7-f87bf5709ad8.png)

**Comment by jakirkham** [comment]
Perfect. Thanks.
