### ISSUE TITLE
Request for updating libjit versions in the tracker

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#78]
The latest release is 0.1.4
xref: http://git.savannah.gnu.org/cgit/libjit.git

Last tracked version is 0.1.2
xref: https://abi-laboratory.pro/?view=timeline&l=libjit

**Comment by linuxhw** [comment]
Fixed. Thanks!

![libjit](https://user-images.githubusercontent.com/15686469/67150376-7c52fe80-f2bf-11e9-8f7f-c0bfc87277aa.png)

**Comment by nehaljwani** [comment]
Thank you very much!
