### ISSUE TITLE
add tiledb

### ISSUE THREAD

**Issue by CJ-Wright** [lvc/upstream-tracker#81]
Would it be possible to add tiledb?

https://tiledb.com/
https://github.com/TileDB-Inc/tiledb/archive/1.7.7.tar.gz

**Comment by linuxhw** [comment]
Hello,

Done: https://abi-laboratory.pro/?view=timeline&l=tiledb

![tiledb](https://user-images.githubusercontent.com/15686469/78003041-bfba9a00-7340-11ea-8202-5f653e7bd032.png)

**Comment by CJ-Wright** [comment]
Thank you very much!

**Comment by CJ-Wright** [comment]
@linuxhw As a side note, is there an API for adding things? Conda-forge has a whole bunch of packages that we track and pin ABI compatibilities. It would be great to have them here but I don't want to inundate you with issues.
