### ISSUE TITLE
Update EASTL

### ISSUE THREAD

**Issue by Neargye** [lvc/upstream-tracker#84]
EASTL release [3.16.07](https://github.com/electronicarts/EASTL/releases/tag/3.16.07) on Jun 11, but on site stiil version 3.13.06 https://abi-laboratory.pro/?view=timeline&l=eastl

**Comment by bsdhw** [comment]
The report has been updated. All looks fine except of several removed private data symbols from eastl::Internal in 3.16.07.

**Comment by Neargye** [comment]
Thanks!
