### ISSUE TITLE
Request for tracking crc32c

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#85]
https://github.com/google/crc32c

**Comment by bsdhw** [comment]
Done: https://abi-laboratory.pro/?view=timeline&l=crc32c

![ABI-0](https://user-images.githubusercontent.com/64436175/94012749-e1f21980-fdb1-11ea-907c-ee6f7cc7afdc.png)

**Comment by nehaljwani** [comment]
Thank you!
