### ISSUE TITLE
Tracker for yaml-cpp is out of date!

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#87]
https://abi-laboratory.pro/index.php?view=timeline&l=yaml-cpp

Latest is 0.6.3 https://github.com/jbeder/yaml-cpp/releases

**Comment by lvc** [comment]
This is now fixed. Thank you!

![ABI-1](https://user-images.githubusercontent.com/1517837/94420427-cfe6f100-018c-11eb-827c-6c05e92abb0e.png)
