### ISSUE TITLE
Request for tracking libexpect

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#89]
https://sourceforge.net/projects/expect/files/Expect/5.45.4/expect5.45.4.tar.gz/download

**Comment by lvc** [comment]
The report has been added at https://abi-laboratory.pro/index.php?view=timeline&l=expect

![ABI-2](https://user-images.githubusercontent.com/1517837/95626151-65825a80-0a82-11eb-92f6-65c473fd91ef.png)

**Comment by nehaljwani** [comment]
Thank you!
