### ISSUE TITLE
Please update tracking for libprotobuf

### ISSUE THREAD

**Issue by nehaljwani** [lvc/upstream-tracker#95]
https://abi-laboratory.pro/index.php?view=timeline&l=protobuf

Latest version is v3.18.1

**Comment by linuxhw** [comment]
Done.

Thank you!

![ABI-4](https://user-images.githubusercontent.com/15686469/138243362-31369f7e-1d33-4d6f-8434-80645cae34b7.png)

**Comment by nehaljwani** [comment]
Awesome!
